openapi: 3.0.3
info:
  title: LT Chat App
  version: 1.0.11
paths:
  /api/chat/msglist/{chatid}:
    get:
      summary: メッセージ一覧取得
      parameters:
        - name: chatid
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                required:
                  - messageid
                  - message
                items:
                  properties:
                    messageid:
                      format: int64
                      example: 1
                    message:
                      type: string
                      example: message

  /api/chat/create:
    post:
      summary: 新規チャット登録
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chatName:
                  type: string
                createDate:
                  type: string
                  format: datetime
                  example: "2023-01-01 00:00:00"
      responses:
        200:
          description: 登録されました。
        # 400:
        #   description: validation error
        # 500:
        #   description: server error
  /api/chat/update:
    put:
      summary: チャット情報変更
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chatId: 
                  type: integer
                chatName: 
                  type: string
                updateDate:
                  type: string
                  format: datetime
                  example: "2023-01-01 00:00:00"
      responses:
        200:
          description: 変更されました。

  /api/chat/delete:
    delete:
      summary: チャット削除
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chatId: 
                  type: integer
      responses:
        200:
          description: 削除されました。